title: Blaž Demšar

author:
  name: Blaž Demšar
  email: "blazdemsar@gmail.com"

description: >
  This is just a description of this website. Honestly, I have nothing fancy to write here. It's just my personal 
  page - duhh!

# theme: minima
remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - about.md
  - journey.md
  - projects.md

minima:
  skin: dark
  social_links:
    - { platform: github,  user_url: "https://github.com/blazdemsar" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/blazdemsar489852174" }
