title: Blaž Demšar

author:
  name: Blaž Demšar
  email: "blazdemsar@gmail.com"

# theme: minima
remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - ABOUT.md
  - EXPERIENCE.md
  - PROJECTS.md

minima:
  skin: dark
  social_links:
    - { platform: github,  user_url: "https://github.com/blazdemsar" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/blazdemsar489852174" }
